### ISSUE TITLE
Let me configure where it saves the file

### ISSUE THREAD

**Issue by scripting** [jcubic/chat-gpt#12]
I have a utility that automatically uploads files to a public S3 location. 

I'd like to be able to use this excellent utility to save it to a calendar-structured sub-folder of that public folder.

I am a programmer and have written bookmarklets. I looked at the code but didn't see clearly enough how to make this kind of change, and i don't want to get out of sync with your changes anyway.

**Comment by jcubic** [comment]
I don't think that you can do that in the Web platform to save files in a given directory. Unless there is some new API that allows opening save as file picker.

**Comment by jcubic** [comment]
Sure you can add any prefix you want, but this is out of the scope of this project. But the code is Open Source you can do whatever you want with it.

This is the code:

```javascript
    a.download = title.toLowerCase()
      .replace(non_letters_re, "-")
      .replace(trailing_dash_re, '') + '.html';
```

You can edit it to make any filename you want.

**Comment by scripting** [comment]
ok, i get the message. i would rather not fork the project because if there are improvements, i want them.

**Comment by jcubic** [comment]
You can fork and sync with upstream. I think that you can even now use the GitHub interface to update the fork even if you have changes.

**Comment by jcubic** [comment]
After consideration I think that I can add `chat-gpt-` prefix to files, it will not hurt and if someone downloads a lot of files they will be next to each other in a file browser.

**Comment by jcubic** [comment]
now the file name is:

```javascript
a.download = `chat-gpt-${slug}.html`;
```

**Comment by scripting** [comment]
Thanks for this change, however i'm getting an error when I run the new version. 

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1686843/223224398-7eb22c01-a3df-4b0d-9a52-8467cd97cfb3.png">

**Comment by jcubic** [comment]
This is what's happening if you don't test the code you write. It should be fixed now.

**Comment by scripting** [comment]
Here's a write-up of what I have working locally thanks to the bookmarklet and the feature you added in this thread. 

http://scripting.com/2023/03/08/153909.html

I am now able to easily use ChatGPT queries in my blog posts. No screen shots. Many advantages. 

_Thanks!_

**Comment by jcubic** [comment]
Nice, I think that I will start a section in README with different usage.
