### ISSUE TITLE
how does it work

### ISSUE THREAD

**Issue by zpenguin360** [jcubic/chat-gpt#14]
i was wondering how it works , just curious

**Comment by jcubic** [comment]
This is a bookmark that has a JavaScript code so the code can do whatever the web application can do, it finds an element on the page and saves it as an HTML file. This is a common thing web apps can do, downloading files that are generated in JavaScript.

**Comment by zpenguin360** [comment]
oh damn thats useful thx

**Comment by salicius** [comment]
I don't understand, i download the js file and after ?

**Comment by jcubic** [comment]
@salicius you need to add the code as a bookmark if you don't how, then open the [website](https://jcubic.github.io/chat-gpt/) and drag and drop the link to your bookmarks. Please read what is [Bookmarklet on Wikipedia](https://en.wikipedia.org/wiki/Bookmarklet).

**Comment by jcubic** [comment]
@salicius I've added this information to README.

**Comment by salicius** [comment]
Thanks a lot! But the generated file doesn't have avatar pictures, idk either it's an error or just my fault

**Comment by jcubic** [comment]
Avatar pictures are not part of the output. I'm not sure if it will good idea to include them since they are part of the website and they probably are not public. I will need to generate Base64 encoded images and embed them into the output HTML, I'm not sure if it's worth it.
