### ISSUE TITLE
Missing table formatting

### ISSUE THREAD

**Issue by sudkish** [jcubic/chat-gpt#15]
When exporting threads with tables, the table borders are not rendered when exporting via the bookmarklet.

**Comment by jcubic** [comment]
Thanks for reporting, do you have an example prompt that renders a table? It will be easier to test.

**Comment by sudkish** [comment]
Generate a plain text table with 6 random terrible reddit user names, one adjective about them, and their reddit karma.

**Comment by jcubic** [comment]
I've added style for tables
