### ISSUE TITLE
KaTeX equations are not rendered properly

### ISSUE THREAD

**Issue by jxy** [jcubic/chat-gpt#16]
You can ask ChatGPT to show equations with a prompt like this.

```
Show math in LaTeX, using \(f(x)\) for inline math and $$f(x)$$ for display math. Now try some inline math and display math.
```

Those equations are poorly rendered from the saved file.

**Comment by jcubic** [comment]
Will check if the output contains LaTeX they can be rendered with MathJax in output HTML.

**Comment by jcubic** [comment]
Fixed
