### ISSUE TITLE
Save icons?

### ISSUE THREAD

**Issue by JonLevin25** [jcubic/chat-gpt#17]
Would be nice if icons could be saved (possible to embed as a binary blob in html somehow?)
Or maybe just replace them with "You:", "Assistant:"/:ChatGPT:" text so it's easier to grok who's who?

**Comment by jcubic** [comment]
I can check what I can do, there was a similar issue (I can't find it) and I've said that this will be out of scope for this project but I think that I can add this.

**Comment by jcubic** [comment]
It should display avatars now

**Comment by JonLevin25** [comment]
It shows only ChatGPT's icon. Makes sense since the other icon is a image from an external URL.
Prob good enough to differentiate at a glance for most situations. Thanks!

**Comment by jcubic** [comment]
I've added base64 encoded URL of the image, it should appear in the output. Can you provide a file with the output?

**Comment by jcubic** [comment]
I will add this as an example since there are changes:

![Przechwycenie obrazu ekranu_2023-04-08_16-00-09](https://user-images.githubusercontent.com/280241/230725249-87d27870-af71-431f-a9e0-8d97b0989954.png)

**Comment by JonLevin25** [comment]
Sure, here's my output.
[chat-gpt-testing-output-assistance.zip](https://github.com/jcubic/chat-gpt/files/11183488/chat-gpt-testing-output-assistance.zip)

**Comment by jcubic** [comment]
Sorry I will not able to help you. I don't have chatGPT Plus to test with GPT4 and it seems that it uses a different DOM structure.

I will create an issue maybe someone that has chatGPT Plus will be able to help. Unless you know JavaScript and want to contribute.
