### ISSUE TITLE
GPT4 Model support

### ISSUE THREAD

**Issue by jcubic** [jcubic/chat-gpt#18]
By investigating the output of the bookmark for model GTP4 (from #17) it seems that it uses a different DOM structure. But I don't have access to chatGPT Plus so I can't update for different models.

If you want to contribute the task is to go to chatGPT change the model to GPT4, investigate the DOM output, and update the code so it still works like for normal chatGPT.

**Comment by hovi** [comment]
Just tried your code with gpt-4 opened chat and it works fine. There are minor unimportant visual disturbances.

**Comment by jcubic** [comment]
@hovi it seems there is a problem with Avatars, but I only saw a screenshot.

**Comment by hovi** [comment]
I don't have avatar so can't help with that one. The disturbance I see is with my text-based avatar is that it isn't squared, but gets bigger and looks slightly weird. For me personally I don't care about that. I am happy that the chat is formatted well and clean.

I looked at it briefly.
Comparing original and generated output, this css added fixes the shape:
```css
.rounded-sm { max-width: 100%; max-height: 100%; }
```
