### ISSUE TITLE
User avatar image saved not properly

### ISSUE THREAD

**Issue by salicius** [jcubic/chat-gpt#20]
Hi, i'm using your last script, but user image is saved cropped, showing just a quarter of the entire picture. 
I attach here the result and the code from my chat inspection of chatgpt if could be useful:
<img width="151" alt="Screenshot 2023-04-11 at 7 38 29 PM" src="https://user-images.githubusercontent.com/78569177/231249310-e6a06af9-5421-4037-8a6f-52e4695a0a57.png">

```
<img
  alt="myemail@mail.com"
  src="/_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Fmy_replaced_gravatar_code%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fda.png&amp;w=64&amp;q=75"
  decoding="async"
  data-nimg="intrinsic"
  class="rounded-sm"
  style="
    position: absolute;
    inset: 0px;
    box-sizing: border-box;
    padding: 0px;
    border: medium none;
    margin: auto;
    display: block;
    width: 0px;
    height: 0px;
    min-width: 100%;
    max-width: 100%;
    min-height: 100%;
    max-height: 100%;
  "
  srcset="
    /_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Fmy_replaced_gravatar_code%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fda.png&amp;w=32&amp;q=75 1x,
    /_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Fmy_replaced_gravatar_code%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fda.png&amp;w=64&amp;q=75 2x
  "
/>
```

**Comment by salicius** [comment]
Firefox browser on MacOS system

**Comment by jcubic** [comment]
Can you check now if the avatar is usable? I've removed the srcset before converting it to base64, which means that it will use a smaller image on MacOS than on the chatGPT website.

If it doesn't look good, I will need to convert both images from the srcset.

**Comment by salicius** [comment]
I tried this new one but it doesn't work :(

**Comment by jcubic** [comment]
It seems that the main image is 64px and only the srcset adds a smaller one.

**Comment by jcubic** [comment]
Can you test now? I've encoded both 1x and 2x images with the output HTML and rendered them in JavaScript. It should work for both MacOS retina and normal displays.

**Comment by salicius** [comment]
ok, now it works, thanks!

**Comment by salicius** [comment]
Picture is ok, but i'm sorry, now the bookmarklet shows this error! (only on certain conversation)
<img width="382" alt="Screenshot 2023-04-12 at 10 46 55 PM" src="https://user-images.githubusercontent.com/78569177/231581187-dc91fc9d-783b-4b04-8c1e-6c936b4eeda4.png">

**Comment by salicius** [comment]
Ok, i tried again and it works, maybe just loading (?)

**Comment by jcubic** [comment]
Yes, it's some kind of loading of the page, I also had the same error. I need to scroll to the top and wait for the images to appear. I will try to wait somehow.

**Comment by jcubic** [comment]
Yes it seems that the images are lazy loaded and srcset is only added when they are visible on the screen.

**Comment by jcubic** [comment]
Added force load function. When the conversation is first loaded the avatars need to be forced to render, this will make the page jump and get back to the original position. It will only jump on the first load.
