### ISSUE TITLE
ChatGPT Bookmarklet using Light Theme

### ISSUE THREAD

**Issue by karimmd** [jcubic/chat-gpt#24]
Thank you so much for the Save chatGPT Bookmarklet. Would it be possible to save the history using the chatgpt light theme? It seems that the saved bookmarklet only shows the conversations using the dark theme. Thanks.

**Comment by jcubic** [comment]
Will check if you can easily detect if the website uses dark mode.

**Comment by jcubic** [comment]
It's been implemented. There is also a dark mode toggle.
