### ISSUE TITLE
Some huge stars (as icons) are appearing on the generated html file

### ISSUE THREAD

**Issue by karimmd** [jcubic/chat-gpt#25]
The bookmarklet was working quite well until Chat GPT made some slight changes in their interface (I guess) on May 12 version. I am not sure whether that is leading to some bigger stars as the icons appearing in the beginning of the generated html or the developer made some changes. I am not sure whether others are also having the similar issue. Now the html viewing experience is not as good as before due to this issue. Here how it looks for ChatGPT 4 (with light version):

![image](https://github.com/jcubic/chat-gpt/assets/6984392/e6191b53-725f-4831-b8af-d9a713632724)

And this is how it looks for ChatGPT 3 (with dark version):
![image](https://github.com/jcubic/chat-gpt/assets/6984392/f5bba29d-9f27-46ff-a4b9-86d9bf31952d)

**Comment by jcubic** [comment]
I don't have chatGPT Plus to test this. But it affects also chatGPT 3, but I can't reproduce it on my end. Maybe share the prompt or upload the file so I can see what are you typing into the chat. I don't see any icons.

**Comment by rowntreerob** [comment]
its the svg in the short attachment causing the stars , appearing just before:

"Model: GPT-4"
[chat-gpt-debt-doom-loop-simulation.txt](https://github.com/jcubic/chat-gpt/files/11478880/chat-gpt-debt-doom-loop-simulation.txt)

**Comment by jcubic** [comment]
I don't have chatGPT plus so I don't know how the model picker and model show up.

Can you show me the screenshot of the chatGPT page? I can just remove that SVG, but I also want to put the model in right position.

**Comment by rowntreerob** [comment]
see edits to above comment with devtools screens

**Comment by jcubic** [comment]
Thanks but I can open the file you send me, I don't need screenshot of that file open in your browser. I need chatGPT interface screenshot and I don't need dev tools. Just generate screenshot of OpenAI website not the generated file.

**Comment by rowntreerob** [comment]
https://htmlpreview.github.io/?https://gist.githubusercontent.com/rowntreerob/3bc8c4a6d6a18a594f144ee62589676f/raw/a9acfb402330aabf98c0cf16e1578b70a0c84337/chat-gpt-iss_25.html

does that help?

**Comment by rowntreerob** [comment]
screenshot from chatgpt domain below 

![Screenshot 2023-05-15 9 14 20 AM](https://github.com/jcubic/chat-gpt/assets/169984/4a387546-351a-481e-a3c4-333d37e70136)

**Comment by jcubic** [comment]
I've created a version of the bookmark on different branch:

https://github.com/jcubic/chat-gpt/blob/model-picker/bookmark.js

Can you test this if it works for the model name (chatGPT plus)? It should also fix the alignment of the avatars, since right now on your file they were off because of the first element with the model name.

**Comment by rowntreerob** [comment]
looks good
1,  replaced the bookmarklet with the link above
2.  opened a dialog from history bar in openai (gpt4
3.  invoked the new bookmarklet that called a download
4. opened the newly downloaded html file on local machine 

![Screenshot 2023-05-15 9 47 11 AM](https://github.com/jcubic/chat-gpt/assets/169984/48ac64b4-05c0-44fe-97c1-ea81ae5d5854)

thanks .. great tool to have!
