### ISSUE TITLE
dom is null

### ISSUE THREAD

**Issue by emsi** [jcubic/chat-gpt#28]
It seems the bookmarklet stopped working and is now erroring out:
`dom is null`
I'm using:
Firefox 114.0.1
[ChatGPT August 3 Version](https://help.openai.com/en/articles/6825453-chatgpt-release-notes)

**Comment by jcubic** [comment]
Will check, do you use the free or paid version of chatGPT?

**Comment by jcubic** [comment]
Yes, got the same error. Will work on this tomorrow.

**Comment by jcubic** [comment]
Should be fixed now.
