### ISSUE TITLE
How to use on Firefox + Linux

### ISSUE THREAD

**Issue by jpcaram** [jcubic/chat-gpt#29]
I'm having no luck getting it to work. I'm using Firefox on Linux. If I understand correctly the steps would be:

1. Create the bookmark (from the link on your web page).
2. Go to chatgpt, have a conversation with it.
3. Go to the bookmarks menu and simply click on the bookmark.

I was expecting the browser to start a download. The only thing that happened is that it scrolled the chargpt conversation to the bottom.

I also tried pasting the contents of bookmark.js into the developer tools console. The return value shows a pending promise and nothing happened.

**Comment by jcubic** [comment]
It seems that the bookmark doesn't work anymore. I don't actually use it recently. So you're the first person who reports an issue.

I need to check. The OpenAI probably changed the website recently when they added this GPT 3.5/4 toggle at the top.

**Comment by jcubic** [comment]
It seems that OpenAI removed responsive images from avatars. There are a lot of code that make sure that it is fully loaded. Open AI was using some lazy loading that now is gone.

This will simply the bookmark but a lot of code need to be refactored.

**Comment by jcubic** [comment]
It should work now. Open AI removed all the HTML related to avatars and used normal images with [Gravatar service](https://gravatar.com/).

**Comment by jcubic** [comment]
If something is not working, don't hesitate to report an issue.

**Comment by jpcaram** [comment]
It works now! Thanks!
