### ISSUE TITLE
Access to image at 'https://s.gravatar ...' has been blocked by CORS policy

### ISSUE THREAD

**Issue by jackusay** [jcubic/chat-gpt#32]
Unable to download. 
When clicking on the bookmarklet, nothing appears.

log in chrome dev (image):
![2024-02-08 14_29_04-List files without  jpg_ png  - Brave](https://github.com/jcubic/chat-gpt/assets/58719891/7b8c6fa4-b4a4-4d3d-85a7-6e2081627577)

log in chrome dev (txt):
```js
Access to image at 'https://s.gravatar.com/avatar/68cec88a58ee58f59e697293ced450e9?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fpe.png' from origin 'https://chat.openai.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
68cec88a58ee58f59e697293ced450e9:1          GET https://s.gravatar.com/avatar/68cec88a58ee58f59e697293ced450e9?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fpe.png net::ERR_FAILED 302
```

**Comment by jcubic** [comment]
Thanks for the report. Will check it out.

**Comment by jcubic** [comment]
Just checked and it works. Tested with GPT 3.5 since I don't have access to chatGPT Plus.

Are you sure you use the latest version of the bookmark? Do you have any browser extensions installed? Can you try in incognito/private mode?
