### ISSUE TITLE
I get a error now with this bookmark trick.

### ISSUE THREAD

**Issue by mullcom** [jcubic/chat-gpt#33]
when i found this i get really happy. Doing so well to get format out from GPT.

But now seams it broken.

i get a error Saying this

Cannot read properties of null (reading 'src')
![image](https://github.com/jcubic/chat-gpt/assets/34793390/30a6d3bb-e713-4ebd-93eb-d8d73338eee9)

**Comment by jcubic** [comment]
Thanks for reporting will check it out.

**Comment by jcubic** [comment]
It looks like user avatars are gone.

**Comment by jcubic** [comment]
It should work now, at least for free version.
