### ISSUE TITLE
Missing Code Block Black Background Can Make Code Unreadable

### ISSUE THREAD

**Issue by git-crj** [jcubic/chat-gpt#34]
The text in code blocks is somewhat unreadable, since the black background is missing:

Original view:
![image](https://github.com/jcubic/chat-gpt/assets/6296032/bb6a42e2-3380-4849-8dd6-3df3e64799dc)

Saved View
![image](https://github.com/jcubic/chat-gpt/assets/6296032/07a7c014-fed0-49a6-9613-0368f5279024)

**Comment by jcubic** [comment]
Thanks for the report, will check. I usually use dark mode, so I didn't notice any problems.

**Comment by jcubic** [comment]
It should be fixed. It don't look as nice as the original, but the code is visible now.

**Comment by jcubic** [comment]
The style can also be improved I've created a separated issue for it: https://github.com/jcubic/chat-gpt/issues/35

**Comment by git-crj** [comment]
It is fixed.  Thanks for the unbelievable fast turnaround time!

![image](https://github.com/jcubic/chat-gpt/assets/6296032/f9051091-9c40-4c8e-979d-40a742b7f785)
