### ISSUE TITLE
Doesn't save chatGPT side 

### ISSUE THREAD

**Issue by francogrex** [jcubic/chat-gpt#37]
It does save a file but only with the input of the user. The chatGPT side of the conversation is blank. Therefore as it stands, this code is not useful to save the chatGPT conversation to a file.

**Comment by jcubic** [comment]
Thanks for the report, I didn't check the bookmark recently. Maybe OpenAI changed something on the website. Will take a look.

**Comment by jcubic** [comment]
The code is fixed, I only need to work a bit on the style. The prompt and response don't align.

**Comment by jcubic** [comment]
I'm closing the issue and Open a new about the style
