### ISSUE TITLE
Configuring commit squashing for pull requests

### ISSUE THREAD

**Issue by oaustegard** [jcubic/chat-gpt#4]
I have a PR but it's messy - 12 commits of iterative tweaks and having difficulties squashing them on my end -- could you allow commit squashing? https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by jcubic** [comment]
It seems that it's enabled by default. I don't usually use squash merge, but maybe I should.
