### ISSUE TITLE
Bookmarklet silently crashes on Firefox

### ISSUE THREAD

**Issue by agladysh** [jcubic/chat-gpt#7]
Error message from the console:

```
Uncaught DOMException: Document.querySelector: 'main > .flex-1 > .h-full .flex:has(> .w-full)' is not a valid selector
```

It would be nice to have an alert or something.

Also, please tell me if I can provide additional diagnostics for the bug itself.

**Comment by jcubic** [comment]
it seems that [:has()](https://caniuse.com/css-has) selector is not supported by Firefox by default.

**Comment by jcubic** [comment]
It turns out that the `:has()` was not actually needed. Should be fixed now

**Comment by jcubic** [comment]
It's automatic as far as I know. But maybe the code is cached.

**Comment by jcubic** [comment]
Cache busting is tracked in #8
